name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: 'Run CMake'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeBuildType: Release  
        buildDirectory: "${{ github.workspace }}/../../_temp/linux"
        buildWithCMake: true
        buildWithCMakeArgs: --config Release  
        
    - name: 'Run CTest'
      run: ctest -C Release
      working-directory: "${{ github.workspace }}/../../_temp/linux"
  
        
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: 'Run CMake'
      uses: lukka/run-cmake@main
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeBuildType: Release  
        buildDirectory: "${{ github.workspace }}/../../_temp/macos"
        buildWithCMake: true
        cmakeAppendedArgs: -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/../../_temp/macos/install"
        buildWithCMakeArgs: --config Release
        
    - name: 'Run CTest'
      run: ctest -C Release
      working-directory: "${{ github.workspace }}/../../_temp/macos"
        
